### ISSUE TITLE
Форма правки данных портит данные по источникам

### ISSUE THREAD

**Issue by Limych** [Limych/GeniBase#10]
форма для правки данных (edit, которая) сейчас портит сведения из raw по источникам (она всегда его берёт нулём и вычисляет по № страницы, вродебы). Сейчас это неправильно! Новые данные (не из списков, а из Разведчика, например) грузятся в raw с уже заполненным source_id
edit-форма его затирает
Это надо не забыть проверить!!!

**Comment by Limych** [comment]
Так… Какой алгоритм теперь должен быть для заполнения source_id, list_nr и прочих полей, связанных с источниками?

**Comment by a-KaDeMi-k** [comment]
source_id я сейчас прописываю руками в файлах для заливки. Т.е., **если в persons_raw это поле заполнено (<>0), то надо на него и ориентироваться** (не пересчитывать при правке в эдиторе).
*Писать в файл id, конечно, не удобно. Но с августа заливок было относительно немного - я справлялся (сначала содавал ручками записи в справочнике, потом загонял id в эксель). Хорошим вариантом было бы придумать, как от этого избавиться. Пока особых идей нема*

list_nr у нас уже потерял актуальность. Это номер списка (№ газеты, журнала). Т.е. характеристика источника. Мы его вынесли в справочник dic_source
Т.о. этот столбец можно удалять и из persons и из persons_raw

Номер страницы, само собой, остаётся и переносится при формализации из raw в основную таблицу. Можно переименовать в source_pg (как сделали в представлении)

**Comment by Limych** [comment]
Ок. `list_nr` из `persons` удаляем сегодня вечером. Можно заодно `list_pg` переименовать в `source_pg`.
Программно я всё подготовил.

**Comment by Limych** [comment]
Done
