### ISSUE TITLE
Новый алгоритм поиска информации в БД

### ISSUE THREAD

**Issue by Limych** [Limych/GeniBase#15]
Оптимизация запросов к СУБД с целью максимального ускорения его работы.

**Comment by a-KaDeMi-k** [comment]
Как бы нам ещё попробовать избавиться от ДУБЛИРОВАННОГО выполнения запросов?!
Ведь, реально, мы один запрос запускаем только для того, чтобы кол-во записей посчитать, а второй - чтобы сами результаты вывести.
ИМХО, не очень оптимально.
Но я не в курсе, может такая технология в web-программировании и применяется всегда.

Кстати, можно счётчик результатов расширить - считать дополнительно к общему кол-ву найденных ещё и включённые в результаты поиска записи по видам ключей.
Т.е., типа:
Всего найдено 381 запись (из них по фонетич. совпадению 300, по графологич. - 120)
Категория "фичи" :)

**Comment by Limych** [comment]
Убрать дублирование выполнения запросов я смог только одним образом: созданием промежуточной таблицы, в которой хранились бы id найденных записей. А уже по ним формировалась бы выборка с полными данными.

ИМХО, это сильно экономило бы время за счёт убирания дублирования запросов на этапе поиска и на этапе переключения между страницами результатов.

**Comment by a-KaDeMi-k** [comment]
Если реализовать через представление, то запрос для id с основными ограничениями можно делать так:
select 
  `p`.`id`
from
  `persons_v2` `p`
/* поиск по фамилии - начало */
  ,(select distinct `k`.`person_id` from `idx_search_keys` `k` where `k`.`surname_key` in ('ХРОЛЕНОК','ХРСЛЕНСН', 'ХРАЛ2')) `isk`
/* поиск по фамилии - окончание */
where 1=1
/* поиск по фамилии - начало */
  and `p`.`id` = `isk`.`person_id`
/* поиск по фамилии - окончание */
/* поиск по региону - начало */
  and (
                `p`.`region_idx`  rlike '[[:<:]]ЧЕРНИГ(..)+[[:>:]]'
       or upper(`p`.`place`     ) rlike '[[:<:]]ЧЕРНИГ(..)+[[:>:]]'
       )
/* поиск по региону - окончание */
order by 'x'
/* поиск по фамилии - начало */
 ,(`p`.`surname` LIKE "%ХРОЛЕНОК%") desc
/* поиск по фамилии - окончание */
 ,`p`.`surname`,`p`.`name`,`p`.`region`,`p`.`place`,`p`.`rank`,`p`.`source`,`p`.`list_pg`

Строки между парами комментариев /* ... - начало */ и /* ... - окончание */ включать в текст запроса на основании заполненности соответствующих префильтров.

Запрос по id, выводящий результаты поиска, тогда может быть такой:
select `p`.*
from `persons_v2` `p`
where 1=1
 and `p`.`id` in (996137,996138,996136,996139)
order by 'x'
 /* поиск по фамилии - начало */
 ,(`p`.`surname` LIKE "%ХРОЛЕНОК%") desc
 /* поиск по фамилии - окончание */
  ,`p`.`surname`,`p`.`name`,`p`.`region`,`p`.`place`,`p`.`rank`,`p`.`source`,`p`.`list_pg`

Сортировку во втором случае повторять надо всё равно, к сожалению

**Comment by Limych** [comment]
Куча недоработок в этих запросах…
Ну ладно, я сам придумал варианты запросов для поиска по именам и для поиска с шаблонными символами.
Но (а) нам нужен вариант запроса расширенного поиска (по всем вариантам использования) и (б) при выдаче результатов поиска на экран нужно знать, где результат из чёткого поиска, а где — из нечёткого.

**Comment by a-KaDeMi-k** [comment]
Напишу, хоть и поздно, наверно.
Поиск по префильтру со знаками подстановки у нас "отключает" фонетический и графологический поиск. Поэтому можно предложить искать по фамильному индексу (тип 1)

...
,(select distinct k.person_id from idx_search_keys k where k.surname_key like ('ХРО%НОК') and k.surname_key_type = 1) isk
...

Чёткий от нечёткого отличаем просто - по наличию символов "*" и "?" в строке префильтра.

**Comment by Limych** [comment]
Не поздно. Но задачу ты не понял…

1) расширенный поиск по всем полям. Нужна формула запроса;
2) результаты поиска. Нужна разметка (в SQL-запросе), где результат найденный по точному совпадению, а где — по нечёткому поиску.

**Comment by a-KaDeMi-k** [comment]
Я, честно говоря, думал, что текущий вариант поиска по ОСТАЛЬНЫМ (не "фамилия" и не "география") полям мы оставляем без изменения...

Для расширенного поиска:
- по списочным полям - добавляем строку типа 
and p.<<имя_поля>> in (список_выбранных_значений)
- по датам
and p.date >= начальная_выбранная_дата
and p.date <= конечная_выбранная_дата
- по номерам страниц
and p.list_pg in (список_выбранных_страниц) - здесь пробелы, ";" надо заменять на ","

По номерам списков (номерам выпусков журналов) надо вьюху (а точнее справочник источников) доделывать - выделить в отдельное поле номера. И тогда, добавив их во вьюху, поиск производить по аналогии с номерами страниц.
Ну и тогда уж и "Тип источника" добавляем во вьюху - поиск по списочному варианту

**Comment by a-KaDeMi-k** [comment]
В результаты поиска добавляем строки:

select
p.* 
,(p.surname LIKE "%ХРОЛЕНОК%") is_not_phonetic_result /*признак поиска не по ключам*/
,sign(instr(p.surname,'*')+instr(p.surname,'?')) is_not_full /*признак наличия * или ? в найденной фамилии*/
from 
persons_v2 p 
where 1=1 
and p.id in (996137,996138,996136,996139) 
order by 'x' 
/* поиск по фамилии - начало */
,(p.surname LIKE "%ХРОЛЕНОК%") desc
/* поиск по фамилии - окончание */
,is_not_full 
,p.surname,p.name,p.region,p.place,p.rank,p.source,p.list_pg

**Comment by a-KaDeMi-k** [comment]
Чего-то я тут с форматированием не пойму %)

В строке sign(instr(p.surname,'*')+instr(p.surname,'?')) is_not_full в первых кавычках звёздочка должа стоять

**Comment by a-KaDeMi-k** [comment]
Блин, звёздочка из первых кавычек в instr пропадает! %)
Что тут, на гите, с ворматированием у меня непонятки

**Comment by Limych** [comment]
Чтобы не было проблем с комментариями, почитай вот эту ссылку: https://guides.github.com/features/mastering-markdown/

Выше пару комментариев я поправил…

**Comment by Limych** [comment]
В простом поиске у нас место ищется по совокупности двух полей:
```sql
… AND CONCAT_WS(",", p.region_idx, UPPER(p.place)) RLIKE "[[:<:]]ЧЕРНИГОВ(..)+[[:>:]]" AND…
```
Есть предложение во view добавить для этого случая единое совокупное поле, вместо того, чтобы городить эту конструкцию в запросе.
Особенно в свете того, что поиск по нескольким словам даёт в запросе аналогичное кол-во таких вот условий.

**Comment by a-KaDeMi-k** [comment]
Не согласен. Конкатенация сразу же исключает использование индекса. Так что для ускорения надо region_idx и place разделять.

**Comment by Limych** [comment]
Ну тогда у нас вынужденно получается монстр вида
```sql
… AND (p.region_idx RLIKE "[[:<:]]ЧЕРНИГОВ(..)+[[:>:]]" OR p.place RLIKE "[[:<:]]ЧЕРНИГОВ(..)+[[:>:]]") AND…
```
… и всё это помножить на число слов в поиске по месту.

Брр…

**Comment by a-KaDeMi-k** [comment]
Это монстр для нас с тобой, а MySQL, думаю, кайфовать будет )))
Надо поэкспериментировать, конечно, может и не стоит овчинка выделки...

**Comment by a-KaDeMi-k** [comment]
Подумалось тут...
А так ли нам нужен RLIKE в географии? Почему мы не можем простым LIKE обойтись? Просто искать подстроку "ЧЕРНИГОВ" без всяких начало/конец слова и т.п.

А в расширенном поиске нормализованные данные по АТД вообще можно в выпадающий список перевести - там тогда по id всё искать с лёту можно будет.
Единственно, сейчас само юзабилити и внешний вид выпадающих списков - "не айс!", ИМХО. Но это - другой вопрос.

**Comment by Limych** [comment]
Переделал географию под LIKE.
Поиск географии по спискам сделаем, когда интерфейс нормальным будет. Сейчас же это неприемлемо.

**Comment by Limych** [comment]
Тонкости поиска.

Если мы ищем «Иванов», а в базе есть «Ив*ов» или «Ив??ов» — эти строки должны находиться. Но я сейчас не уверен, что поиск работает именно так.

Надо проконтролировать…

**Comment by a-KaDeMi-k** [comment]
Да, всё забывал про это написать.
Тут, как минимум, нужно проводить "обратную" операцию. Т.е., все записи с фамилиями, содержащими знаки подстановки, проверять в качестве ограничения на единственную искомую фамилию.
```sql
...
union
select 
  p.id
from
  v_persons p
 ,(
   select distinct k.person_id from idx_search_keys k
   where 1=1
    and (k.surname_key like '%*%' or k.surname_key like '%?%') 
    and (
                'ХРОЛЕНОК' like replace(k.surname_key,'*','%')
            or 'ХРОЛЕНОК' like replace(k.surname_key,'?','_')
            or 'ХРСЛЕНСН' like replace(k.surname_key,'*','%')
            or 'ХРСЛЕНСН' like replace(k.surname_key,'?','_')
            or 'ХРАЛ2'         like replace(k.surname_key,'*','%')
            or 'ХРАЛ2'         like replace(k.surname_key,'?','_')
            )
   ) isk
where 1=1
  and p.id = isk.person_id
...
```
Вот здесь бы поле-признак содержания знаков подстановки в фамилии тоже пригодилось. Даже не признак, а сразу строка, подставляемая в like. Т.е., если в записи есть звёздочка, то в это поле пишем ИВ%ОВ, если знаки вопросов - ИВ__ОВ

А вот как быть, если ищем Ив***нов, а у нас в базе те же Ив***нов и Ив??ов !!!! %)

Кстати, пару вопросов по функции для построения ключей:
1)  в db_update при записи ключей в таблицу надо ещё и их тип проставлять
2) мне кажется, что уже писал где-то, но повторюсь...
Вот у нас есть, допустим, для графологического ключа, такие варианты взаимозамены (а не однонаправленной замены, кстати!): "Н" <=> "К" и "О" <=> "С". Берём фамилию "Семенов". Сейчас функция строит индекс ОЕМЕКСВ. Т.е., всего один вариант, в котором СРАЗУ применены ВСЕ подстановки. Но, по моему, надо генерить их целую кучу:
СЕМЕНСВ
СЕМЕКОВ
СЕМЕКСВ
ОЕМЕНОВ
ОЕМЕНСВ
ОЕМЕКОВ
ОЕМЕКСВ
Тут то мы и помрём! :) :) :)

**Comment by Limych** [comment]
> А вот как быть, если ищем `«Ив*нов»`, а у нас в базе те же `«Ив*нов»` и `«Ив??ов»` !!!! %)

Ну при поиске `«Ив*нов»` вариант `«Ив*нов»` и сейчас найдётся. Если же сделаем обратный вариант, то и он нормально найтись должен.

Я думаю, что надо в таблицу ключей ввести новое поле, которое заполнять уже подготовленной маской для LIKE в том случае, если исходный текст введён с метасимволами.
При вводе метасимволов нечёткий поиск отключается, так что дополнять нужно только строгие ключи (search_key_type = 1). И сравнивать только с исходной фамилией. По наличию в таблице заполненного поля можем и выборку делать, отбрасывая заведомо бесполезные сравнения.

Плюс всегда помним, что может быть введена фамилия из двух и более слов — это также необходимо отрабатывать (кроме того, это задел на перенос имён-отчеств в общую таблицу).

По графологическому нечёткому поиску я намеренно выделил отдельную тему — он толком не сделан и там не всё так однозначно, как может показаться.
Так что тут его предлагаю пока обсуждать лишь в смысле, что он тоже когда-то будет. Сейчас же его почти нет…

**Comment by a-KaDeMi-k** [comment]
Ввёл поле surname_mask.
Вроде бы срабатывает :)
```sql
SELECT *  FROM `idx_search_keys` WHERE 'ИВАНОВ' like `surname_mask`
```

**Comment by a-KaDeMi-k** [comment]
В db_update надо про surname_mask не забыть

**Comment by Limych** [comment]
Сделано.
Но пока не работает подобный поиск по именам.
И делать его не вижу смысла — намного разумнее позже имена перевести на те же рельсы, что и фамилии — тогда поиск сам заработает.

**Comment by a-KaDeMi-k** [comment]
Согласен. По именам всё не так критично и актуально

**Comment by a-KaDeMi-k** [comment]
По сортировке, в принципе, я уже выше приводил вариант
```sql
select
p.* 
,(p.surname LIKE "%ХРОЛЕНОК%") is_not_phonetic_result /*признак поиска не по ключам*/
,sign(instr(p.surname,"*")+instr(p.surname,"?")) is_not_full /*признак наличия * или ? в найденной фамилии*/
from 
persons_v2 p 
where 1=1 
and p.id in (996137,996138,996136,996139) 
order by 'x' 
 is_not_phonetic_result desc
,is_not_full 
,p.surname,p.name,p.region,p.place,p.rank,p.source,p.list_pg
```

**Comment by Limych** [comment]
Сделано.
