### ISSUE TITLE
Индикатор исполнения запроса

### ISSUE THREAD

**Issue by Limych** [Limych/GeniBase#2]
когда нажимаешь кнопку "Поиск", внешне ничего не происходит, и поначалу реакция поисковой системы непонятна.
Можно ли поставить какой-нибудь индикатор того, что "процесс пошел"?

**Comment by Limych** [comment]
Не вижу смысла это делать. Ответ от поисковика идёт довольно быстрый.

**Comment by a-KaDeMi-k** [comment]
Это от кого задача то шла? От Николая что ли?
