### ISSUE TITLE
Перевод всего встроенного в систему текста на gettext. Английская и русская локализации системы

### ISSUE THREAD

**Issue by Limych** [Limych/GeniBase#20]
Одновременно перевод системы на английский язык.

**Comment by Limych** [comment]
Тема для размышлений:
Автоматика сама предлагает наилучший язык интерфейса для пользователя. Но она может и ошибаться… Каким (и где) будем делать меню принудительного выбора языка?

**Comment by a-KaDeMi-k** [comment]
Это хорошо, что ты спросил! Мне не пришлось :)

Мне кажется, что в текущий дизайн сайта лучше всего впишется выпадающее меню с текстовыми названиями версий локализации.
Флаги не вписываются точно - он у нас минималистский, а это лишнее пятно цвета.
Полная строка со всеми доступными языками - тоже не для нас. У нас процент посещений иноязычных мал - надо ориентироваться на русский, а всё остальное - опционально, т.е. скрыто до поры до времени.

А что с украинским, как думаешь? Или все бывшие союзные пусть по-русски работают?

**Comment by Limych** [comment]
На украинский и прочие «союзные» специально заморачиваться переводить я не буду, т.к. не вижу смысла в этом: большинство людей из этих стран прекрасно знают русский язык.

Но если найдутся добровольцы, которые сделают перевод, препятствовать им не буду, конечно…

**Comment by a-KaDeMi-k** [comment]
Напишу в Беседку. Кто отзовётся - хорошо... Нет - так нет.

**Comment by Limych** [comment]
Не надо писать, пожалуйста.

**Comment by a-KaDeMi-k** [comment]
Думаешь, я не справлюсь?

**Comment by a-KaDeMi-k** [comment]
Там же теперь чисто механическая работа, как я понимаю?

**Comment by a-KaDeMi-k** [comment]
Предполагаю, что Роман Коренев, кажется, с ивритом может откликнуться, да и украинский кто-нибудь - максимум

**Comment by Limych** [comment]
Денис,
Ты тратишь силы на те части проекта, которые не несут ему полезного смысла.
Я затеял переводы лишь потому, что всё равно вынужденно переключал систему на работу через gettext. Для этого по правилам необходимо все тексты исходно писать по-английски.

На этом можно было и остановиться. Но коль скоро был явный спрос на немецкий и польский, я решил и их добавить. А также, добавить финский, который был частью РИ, но далёк от русского.
При этом я намеренно не занимаюсь этим сам, а неспешно ищу помощников…

Спрашивается, зачем «упираться рогом», трубить клич и стараться сделать ещё кучу языков? Мы уже переделали все другие более важные дела?

Мы уже привели все справочники в идеальное состояние? Мы уже сделали корректно работающие инструменты редактирования базы? Закончили выверку всех данных в базе?…

Пожалуйста, давай второстепенные работы пока оставим в покое.
