### ISSUE TITLE
Выделение в таблице логов поиска запросов от сторонних поисковых роботов

### ISSUE THREAD

**Issue by Limych** [Limych/GeniBase#26]

**Comment by a-KaDeMi-k** [comment]
А по каким признакам ты думаешь их отсеивать? Что-то я не могу их выцедить из существующей в таблице логов информации.

**Comment by Limych** [comment]
Банально… По поведению. Они никогда не будут запрашивать пустую форму поиска… а ещё никогда не будут сохранять куки… а ещё между запросами страниц у них или очень мало, или очень много времени проходит. (но «очень мало» мы быстро пресекаем ;) )

**Comment by a-KaDeMi-k** [comment]
Ну, всё таки, не по текущей версии таблицы логов... Я, собственно, про это.

**Comment by a-KaDeMi-k** [comment]
Смущают меня что-то текущее соотношение в типах обращений.
С 2015-03-05 18:05:06 по 2015-03-07 13:05:00 помечено как "робот" 6529 запроса (82.4%), а от людей - всего 1395 (17,6%)
Есть какой-нибудь другой, сторонний способ проверить эту статистику? Не знаю, может по http://1914.svrt.ru/stat/ : там же есть данные "Роботы/Пауки посетители"

И ещё. Насколько я понял скрипт, ты сейчас идентифицируешь робота по двум признакам: формат скрипта запроса(?) и адрес, с которого он поступил.
Может мы сделаем признак is_robot более точным? Ноль - так и оставим для людей, 1 - робот, определённый по адресу, 2 - по формату и т.д.

**Comment by a-KaDeMi-k** [comment]
Странные какие-то запросы от роботов. Вернее, совсем неотличимые по смыслу от человеческих.
У меня даже мысль была, что чел набивает в яндексе фамилию, а уж яндекс её "набивает" у нас.
Но это имеет более-менее смысл для полных слов - фамилий, географич. названий.
А у нас роботом помечены, например,* Сте* Иг* * или * ?омер* *. Не укладывается у меня в голове, как робот такие запросы "придумывает". Не понимаю я, наверно, чего-то :(

**Comment by Limych** [comment]
Робот их берёт из подвала. Из ссылок на последние запросы. Именно для того я их и сделал. ;)

**Comment by a-KaDeMi-k** [comment]
Т.е. робот повторно прогоняет запросы, которые ранее были выполнены?! %)
Да-а-а, что-то в логике у меня сбой какой-то

P.S.: но я, например, иногда гоняю запросы из подвала :) на которых глаз остановился и которые заинтересовали )))

**Comment by Limych** [comment]
Робот ничего не придумывает. Он просто тупо ходит по ссылкам.

**Comment by a-KaDeMi-k** [comment]
ясно.
надо будет на досуге проверить  наличие идентичных роботовским запросам в более ранних записях логов

**Comment by a-KaDeMi-k** [comment]
Чтоб не потерялся. Вдруг пригодится
```sql
SELECT
query
, sum(case when `datetime` < '2015-03-05 18:05:06' then 1 else 0 end) unknown
, sum(case when (is_robot = 0) and (`datetime` >= '2015-03-05 18:05:06') then 1 else 0 end) human
, sum(case when (is_robot = 1) and (`datetime` >= '2015-03-05 18:05:06') then 1 else 0 end) robot
, count(*) total
FROM `logs`
group by
query
ORDER BY `total` desc
```

**Comment by Limych** [comment]
Сделано
