### ISSUE TITLE
Навести порядок в таблицах основной базы данных

### ISSUE THREAD

**Issue by Limych** [Limych/GeniBase#28]
Удалить ненужные таблицы/поля, привести все имена к нормальной форме.

Переименования таблиц базы:
* ~~`dic_marital` → `dic_maritals`~~
* ~~`dic_rank2rank` → `dic_rank2id`~~
* ~~`dic_reason` → `dic_reasons`~~
* ~~`dic_reason2reason` → `dic_reason2id`~~
* ~~`dic_region` → `dic_regions`~~
* ~~`dic_religion` → `dic_religions`~~
* ~~`dic_source` → `dic_sources`~~
* ~~`dic_source_type` → `dic_source_types`~~
* ~~`dic_user` → `dic_users`~~

Переименование/Удаление полей таблиц/вьюшек:
* `persons`:
 * ~~`list_nr` → ×~~
 * ~~`list_pg` → `source_pg`~~
* `dic_source`:
 * ~~`pg_correction` → `source_pg_corr`~~
* `v_persons`:
 * ~~`source_pg_correction` → `source_pg_corr`~~
 * ~~`list_pg` → `source_pg`~~

**Comment by a-KaDeMi-k** [comment]
Поле bakup из таблицы ключей удалил.
Добавил поле comments в таблицу dic_source

Надо поменять поле comments в представлении v_persons с
```sql
sc.comments AS comments
```
на
```sql
trim(leading char(10) from concat_ws(char(10),trim(p.comments),trim(sc.comments))) AS comments
```

**Comment by a-KaDeMi-k** [comment]
Добавляем столбец номера выпуска в источники
```sql
ALTER TABLE `dic_source`  ADD `source_number` INT(10) NOT NULL DEFAULT '0' COMMENT 'Номер выпуска/журнала/газеты и т.п.' AFTER `source`,  ADD INDEX (`source_number`) 
```
и данные в него
```sql
update dic_source
set source_number = 
substr(concat(replace(source,'№ ','№'),' '),locate('№',concat(replace(source,'№ ','№'),' '))+1,locate(' ',concat(replace(source,'№ ','№'),' '),locate('№',concat(replace(source,'№ ','№'),' '))+1)-locate('№',concat(replace(source,'№ ','№'),' '))-1)+0
```

**Comment by a-KaDeMi-k** [comment]
Теперь, в принципе, столбец list_nr в persons ненужен. Номер выпуска/журнала можно тянуть из dic_source.
Для этого надо во вьюшке заменить
```sql
,p.list_nr as list_nr
```
на
```sql
,sr.source_number as list_nr
```
Пока не меняю.

**Comment by a-KaDeMi-k** [comment]
Изменил вьюшку!!!
```sql
,`sc`.`source_type_id` as `source_type_id`
,`sc`.`source_number` as `list_nr`
,trim(leading char(10) from concat_ws(char(10),trim(`p`.`comments`),trim(`sc`.`comments`))) AS comments
```

**Comment by a-KaDeMi-k** [comment]
10 записей во вьюшку не попадают!!!
```sql
SELECT * FROM `persons` p where not exists (select 'x' from `v_persons` vp where vp.id = p.id)
```
Очевидно из-за p.source_id = 0.
Разбираюсь, откуда там опять ноль появился. Пока подозрение на форму для редактирования/формализации. Но я ею не пользуюсь давно.

**Comment by Limych** [comment]
Вьюшка у нас используется только в новой версии, потому я внёс правки в неё для большей логичности (переименовал поля):
```sql
`sc`.`source_number` AS `source_nr`,
`p`.`list_pg` AS `source_pg`,
`sc`.`pg_correction` AS `source_pg_correction`,
```

**Comment by Limych** [comment]
Форму для редактирования можно принудительно отключить, вставив в первые строки команду
```php
die('Скрипт временно не работает');
```

**Comment by a-KaDeMi-k** [comment]
Нет, не форма. В файлах заливки (в исходных данных) пропуски.
Как Шерлок пытаюсь понять, что должно быть на их месте. Три поправил. :)

**Comment by a-KaDeMi-k** [comment]
А половина дублей было. Исправил/удалил, но осадочек (откуда взялись?) остался

**Comment by Limych** [comment]
А что за новое поле `source_type_cnt`?!…
Я же просил все правки в базе заранее согласовывать со мной!

**Comment by a-KaDeMi-k** [comment]
Сорри!
Оно называлось source_cnt. Переименовал однотипно с остальными справочниками.
Кол-во источников данного типа.

**Comment by Limych** [comment]
таблицу persons_raw_bak надо бы удалить…

**Comment by Limych** [comment]
И навести порядок в именах таблиц — часть названий во множественном числе (`dic_search_key_types` — правильно), часть — в единственном (`dic_reason` — неправильно)

**Comment by a-KaDeMi-k** [comment]
persons_raw_bak - понимаю твоё стремление, но "есть не просит", а несколько раз я пытался по ней прояснить ситуацию "что было/что стало"
tmp использовал при переделке структуры справочников, кажется - да, можно чикнуть

с именами - надо как-то запланировать, потому как это одновременная правка и php  
давай, для начала, составим список переименований

**Comment by Limych** [comment]
Дык… Составь. :)

**Comment by Limych** [comment]
Интересные дела. У нас в таблице ключей есть 151 уникальных `person_id`, которых нет в таблице `persons`…

**Comment by a-KaDeMi-k** [comment]
Это, наверно, мои проделки.
Удалял дубли из persons (и persons_raw), а про ключи и не вспомнил.
151 - немного многовато, конечно, но вполне возможно.

Можно спокойно удалять.

**Comment by Limych** [comment]
Ага. Найти бы их ещё :)

**Comment by a-KaDeMi-k** [comment]
Удалил индекс person_id из idx_search_keys - он полностью перекрывался primary key

**Comment by a-KaDeMi-k** [comment]
Ща найду и удалю

**Comment by a-KaDeMi-k** [comment]
353 записи для 151 айдишника - в минус

**Comment by Limych** [comment]
Переименования таблиц базы:
* `dic_reason2reason` → `dic_reason2id`
* ~~`dic_rank2rank` → `dic_rank2id`~~

Переименование/Удаление полей таблиц:
* `persons`:
 * `list_nr` → ×
 * `list_pg` → `source_pg`

**Comment by Limych** [comment]
В обновлялку добавлено автоматическое удаление ключей, для которых нет записей в `persons`.

**Comment by Limych** [comment]
Во вьюшку `v_persons` добавлены поля `date_from` и `date_to`

**Comment by a-KaDeMi-k** [comment]
В обновлялку, кстати, ещё можно зашить ежесуточное тех. обслуживание базы - дефрагментация и т.д.
Что там ещё у MySQL есть?

**Comment by Limych** [comment]
Нет, это зашивать не будем…

**Comment by Limych** [comment]
Done

**Comment by a-KaDeMi-k** [comment]
Таблица ```dic_reason``` поле ```reason```
Переименовать всё в ```event````, т.к. у нас уже не причины, а более широко - события
