### ISSUE TITLE
Не работает расширенный поиск

### ISSUE THREAD

**Issue by a-KaDeMi-k** [Limych/GeniBase#33]
По № списка выдаёт пустой результат. К тому же кол-во возвращённых записей пишет равным 1.

**Comment by Limych** [comment]
Мне сложно исправлять ошибки, если нет примера запроса, создающего ошибку.

**Comment by a-KaDeMi-k** [comment]
Любой номер в расширенном поиске вводи. 306, например

**Comment by a-KaDeMi-k** [comment]
Наверно, из-за изменения вьюшки. Я ж перенес № выпуска из persons в dic_source

**Comment by Limych** [comment]
Может вообще удалить из формы поля «номер списка» и «номер страницы»? У нас ведь уже давно не только списки в базе…

**Comment by Limych** [comment]
Удалил эти поля из расширенного поиска.

**Comment by a-KaDeMi-k** [comment]
Не надо удалять!
Надо наоборот добавить поле "Тип источника" (списки, разведчик, губернские - есть справочник) 
И тогда выбирать тип + № источника.
Не знаю, как другие, а я постоянно пользовался обоими полями. Страницами в особенности.

А в чём там сложность возникла?

**Comment by Limych** [comment]
Хорошо… Я вернул на место поле номера страницы.
А вот поле «Источник» добавишь ты в качестве домашнего задания. :)

Исходники кода — см. тут. Правку пришлёшь как pull request тут же.

**Comment by a-KaDeMi-k** [comment]
не понял как это сделать "Правку пришлёшь как pull request тут же."

**Comment by Limych** [comment]
Это значит, сделать fork кода (это делать bs уже умеешь), внести в него все нужные правки, проверить его на работоспособность, после чего отправить запрос на внесение твоих изменений в основной поток кода: https://github.com/Limych/GeniBase/pulls

**Comment by a-KaDeMi-k** [comment]
Я, кажись, в основной ветке поменял... Сорри!
У меня fork есть (ты, вроде бы делал), но в нём всё старое - никак не разберусь, как в него новое залить.
Там же и гостевая книга, которой нет в мастере, ещё что-то - даже не помню что. Старьё какое-то!
Или ещё один fork сделать?

**Comment by Limych** [comment]
Не боись, испортить у меня в коде не получится — перед применением правок я их вижу и могу отклонить. Или постфактом вернуть код в исходное состояние.

Pull request у тебя получился нормальный. только он ни о чём, потому я его сейчас отклоню.

А с форком дела так обстоят: у тебя есть три репозитория: upstream — это тот, от которого ты сделал форк (т.е. мой), origin — это твой форк на гитхабе и local — это твоя локальная копия форка.

Правки ты делаешь всегда в локальной копии. А вот синхронизироваться можешь с любой из двух оставшихся. Только с моей (upstream) — лишь с моего ведома и разрешения.

Для начала, т.к. твоя копия сильно устравшая, её нужно синхронизировать с последними моими правками.
Для этого надо сделать pull из upstream в твою локальную копию.
```
git remote add upstream https://github.com/Limych/GeniBase.git   (при необходимости)
git pull upstream master
```
В результате в локальную версию применятся все мои последние правки. При этом учти, что все твои правки, которые ты вносил в момента создания форка, останутся (они сольются с моими; в случае конфликтов тебе сообщат, где и какой конфликт — его придётся править ручками).

После завершения слияния стоит отправить правку в твой origin:
```
git push origin master
```

Потом вносишь новые правки, опять сабмитишь в свой origin и отправляешь из него pull request в upstream.

Подробнее тут: http://superuser.com/questions/456145/how-can-i-resync-a-fork-from-original

**Comment by a-KaDeMi-k** [comment]
Дело в том, что перед pull request я (по дурости) внёс исправления напрямую - в ветку master. Ну, с локального репозитария, конечно.
Это потом я уже создал fork и, внеся там чисто косметические правки, сделал request. Поэтому он и был "ни о чём"...

**Comment by Limych** [comment]
Не боись… Испортить тут что-либо весьма нетривиальная задача. Для того эта система и создана, чтобы хранить информацию.

**Comment by Limych** [comment]
Кстати, как вариант, учитывая кол-во внесённых мною правок, ты можешь не накатывать изменения на свою старую версию, а банально её уничтожить, после чего создать новый форк.

**Comment by Limych** [comment]
Fixed

**Comment by a-KaDeMi-k** [comment]
нашел крутой баг! :)
у нас в расширенном поиске галки по-умолчанию не стоят, а результаты выдаются расширенные
ну и на них, на галки, он - результат, естественно, не реагирует ))

**Comment by Limych** [comment]
У меня работает всё корректно.
