### ISSUE TITLE
Копилка для мелких багов/правок

### ISSUE THREAD

**Issue by a-KaDeMi-k** [Limych/GeniBase#37]
~~1) Расширенный поиск, список событий - неверная сортировка строк.
Мне добиться решения не удалось~~

~~7) Инструкция для пользвателей: 
"В списках можно выбирать по нескольку значений. Для этого кликайте мышью держа зажатой клавишу «Ctrl» («Command» для Mac)."
Предлагаю добавить: "Повторный клик по выбранному значению с зажатой клавишей позволяет отменить выбор". 
А то я вот, например, далеко не сразу до этого допёр. :)~~

~~15) сообщение "*В полях «Страница источника» и «ID записи» можно перечислять по нескольку значений через запятую или пробел.*" нет «*Номер источника*»
Извращение, конечно, но можно формировать эту фразу динамически - на основе массива цифровых полей.~~

~~16) футер всех страниц - слова о принципах размещения и использования данных базы.
Мне кажется, что "**Обратите внимание:**" тут не подходит. Надо что-то типа "(Copyright)" - вначале, "(с)" - в конце, или вообще ничего. Вообщем, подумать над этим...~~

22) additional_info из результатов у нас ушло - надо возвращать (и думать про поиск по нему - как бы не пришлось его в основную таблицу persons для этого добавлять)

**Comment by a-KaDeMi-k** [comment]
7) Инструкция для пользвателей: 
"В списках можно выбирать по нескольку значений. Для этого кликайте мышью держа зажатой клавишу «Ctrl» («Command» для Mac)."

Предлагаю добавить: "Повторный клик по выбранному значению с зажатой клавишей позволяет отменить выбор". 
А то я вот, например, далеко не сразу до этого допёр. :)

**Comment by a-KaDeMi-k** [comment]
8) Может имеет смысл поменять ссылку "Обсуждение сервиса" на корневую  раздела (http://forum.svrt.ru/index.php?showforum=127) вместо "Беседки"?

**Comment by a-KaDeMi-k** [comment]
9) На страницу "Команда проекта" добавить ссылку/инстукцию "как к нам присоединиться"
Пока что можно вот эту http://forum.svrt.ru/index.php?showtopic=7282
Потом, возможно, что-то специальное приумаем.

10) на форуме вопрос о списке команды задал - там сейчас (уже) не все

**Comment by Limych** [comment]
По поводу команды проекта.
Имя человека ставим перед фамилией — не иди на поводу советских бюрократов, которым было удобнее работать, когда фамилия шла первой.

**Comment by a-KaDeMi-k** [comment]
Привычка свыше нам дана... :)
Может тогда имя - более светлым шрифтом? Сортировка всё равно пофамильная? Отчества нужны?
У меня чёткого ответа на эти вопросы нет. Есть агрументы и "за" и "против"

**Comment by Limych** [comment]
Пишем так, как сейчас. Нафига отчества? Нафига приукрасы?…

**Comment by a-KaDeMi-k** [comment]
Только в плане того же (но уже небюрократического) удобства )))

**Comment by a-KaDeMi-k** [comment]
11) как думаешь, может есть смысл выводить в результатах расширенного поиска в подвальчик id записи? Мне, как человеку, участвующему в разработке было бы удобно. Продвинотому пользователю... Ну, проще нам сообщать об ошибках, например.
Не баг, конечно! В качестве предложения/вопроса ;)

**Comment by a-KaDeMi-k** [comment]
Да! По команде! Я ж создал таблицу в своё время! ИМХО, можно на основе её данных генерить страницу. Только роли/степени участия добавить.

**Comment by Limych** [comment]
2), 3), 4) — это вопрос переработки поисковой формы. Заодно надо сделать и поддержку мобильный браузеров.

**Comment by Limych** [comment]
Зачёркнутые выше записи — исправлены.

**Comment by a-KaDeMi-k** [comment]
12) убрать простановку обрамляющих кавычек в названии источника при выводе результатов

**Comment by a-KaDeMi-k** [comment]
13) внешний вид данных из составного поля comments в результатах поиска, по-моему, не очень коррелируют с текущим оформлением страницы
Посмотреть можно любую запись из типа источника «Комитет Ставропольского края по делам архивов (официальный сайт)»

**Comment by Limych** [comment]
12) — причина?

**Comment by a-KaDeMi-k** [comment]
12) потому, что в самом названии источника кавычки могут встречаться

**Comment by a-KaDeMi-k** [comment]
14) Расширенный поиск, префильтр дат. Можно ли как-то сделать, чтобы при выборе первой даты стоял не ноябрь 1918-го, а июль 1914-го?

**Comment by Limych** [comment]
12) Ну и пусть себе встречаются… Одно другому не мешает.
Можно, конечно, заморочиться и сделать автоматическую правку кавычек по правилам типографики. Но большого смысла в этом, честно говоря, не вижу.

14) нет.
Выпадающее окно — системное. Я им никак не управляю. Более того, оно в разных браузерах и на разных платформах может быть разным. Как и вообще отсутствовать…
Судя по всему, система пытается показать ближайшую к текущему моменту из доступных дат.

**Comment by a-KaDeMi-k** [comment]
12 - строка "Первое "Второе третье"" смотрится не очень. Вот в чём смысл то обрамлять ещё раз кавычками? :)

14) может тогда выводить их сразу заполненными, а не пустыми. В максимальном (по базе) диапазоне?
Хотя... Тогда отсеются записи без дат :(
Ладно, пусть тогда остаётся, как есть

**Comment by Limych** [comment]
12) Правильный вариант с т.з. пунктуации русского языка: «Первое „Второе третье“» могу его сделать — я не гордый… А то, что ты написал — это знаки дюйма, а не кавычки ;)

**Comment by a-KaDeMi-k** [comment]
12) я бы всё таки убрал обрамляющие. Если уж они так будут нужны - заведём на соответствующей записи в таблице источников

14) пока вычеркнул

**Comment by a-KaDeMi-k** [comment]
15) сообщение "В полях «Страница источника» и «ID записи» можно перечислять по нескольку значений через запятую или пробел." нет «Номер источника»
Извращение, конечно, но можно формировать эту фразу динамически - на основе массива цифровых полей.

16) футер всех страниц - слова о принципах размещения и использования данных базы.
Мне кажется, что "**Обратите внимание:**" тут не подходит. Надо что-то типа "(Copyright)" - вначале, "(с)" - в конце, или вообще ничего. Вообщем, подумать над этим...

**Comment by a-KaDeMi-k** [comment]
Может скопировать все пункты в первое сообщение, чтоб оттуда вычёркивать, а не бегать по всей теме?

**Comment by a-KaDeMi-k** [comment]
25) обтримивать (trim) все введённые в префильтры строки
Случайно завёл " Алексей" - ничего не обнаружилось

**Comment by Limych** [comment]
25) — поясни. Где вводил?

**Comment by Limych** [comment]
Перенёс всё в первое сообщение.

НО вообще лучше больше не добавлять сюда пунктов. Пусть лучше будет сто тем с мелкими багами, по одной на каждый, чем это хайло разрастётся до такого размета, что невозможно будет в нём ориентироваться…

**Comment by a-KaDeMi-k** [comment]
" Алексей" вводил в поле "Имя Отчество" в простом поиске

**Comment by Limych** [comment]
19, 24 — fixed

**Comment by a-KaDeMi-k** [comment]
20) не вижу, где ты поправил?
Насколько я понимаю, формализатор использует ограничение по датам из файла *class.ww1-database.php*. А там так и стоит
```php
if(!defined('MIN_DATE'))	define('MIN_DATE', '1914-07-28');
```
Проапдейтил статус неформализовавшихся в *Draft*, так они опять в *Cant publish* полезли

**Comment by Limych** [comment]
http://1914.svrt.ru/edit/publish.php

**Comment by a-KaDeMi-k** [comment]
Хм...
А разве не в ../gb/publish.php функция формализации?
```php
	 /*
	 * Функция нормирования дат
	 */
	function prepublish_date(&$raw, &$date_norm){
		if(empty($raw['date'])){
			$raw['date_from']	= MIN_DATE;
			$raw['date_to']		= MAX_DATE;
			return;
		}
```
Edit - это же форма редактирования... Причём некорректно работающая сейчас

**Comment by Limych** [comment]
1. Да, функция формализации там. где ты указал
2. А почему ты уверен, что форма редактирования работает некорректно? :)

**Comment by a-KaDeMi-k** [comment]
У нас есть тема с багом - форма портит id источника - кажется, вычисляет его на основе № страницы.
Она заточена была на списки потерь - там по 16 страниц на номер, кажись

**Comment by Limych** [comment]
1. C чего ты это взял? Докажи!
2. Ок. Принято…

**Comment by a-KaDeMi-k** [comment]
Да, кроме дат, ещё и "Событие" держало... Награждения 1-ой степенью в справочнике не было...
Процесс пошёл

**Comment by a-KaDeMi-k** [comment]
Но на что тогда всё таки MIN_DATE и MAX_DATE влияют?
Мне казалось, что всё выходящее за их диапазон метилось как Cant Publish

**Comment by Limych** [comment]
Верно…
Вот только этих констант не существовало ещё вчера утром, а были жёстко забитые даты и совсем иные.

**Comment by Limych** [comment]
Для п.1 списка не могу найти решение — не понимаю, почему MySQL так сортирует строки… :(

**Comment by Limych** [comment]
8 - fixed

**Comment by a-KaDeMi-k** [comment]
по п.1 я тоже всю голову сломал
и явно COLLATE пытался указывать - пофиг!

**Comment by Limych** [comment]
13 - не является ошибкой. Всё там ок. Вычеркнул.

**Comment by Limych** [comment]
Перестань добавлять сюда новые пункты в список! Пункты сверх 25-го я буду игнорировать.

**Comment by Limych** [comment]
22) — см. #47

Остальные пункты закрыты. Issue закрываю.
