### ISSUE TITLE
Сделать нормальное оформление форм поиска

### ISSUE THREAD

**Issue by Limych** [Limych/GeniBase#39]

**Comment by a-KaDeMi-k** [comment]
Меня ещё чуть-чуть смущают надписи у галочек в расширенном поиске.
Может быть как-то переформулировать?
- "использовать фонетический и графологический поиск"
- "дополнить сокращёнными вариантами написаний"

**Comment by Limych** [comment]
Надписи нормальные. Не заморачивайся…

**Comment by Limych** [comment]
fixed
