### ISSUE TITLE
Поиск по отчеству. Баг?

### ISSUE THREAD

**Issue by a-KaDeMi-k** [Limych/GeniBase#58]
Что-то либо опять я туплю, либо поиск недоделанный, либо справочник имён по Яковлевич/Яковлев пустой (проверить сейчас не могу).

Но *Макаров* + *Яковлевич* из _Перм_ской губернии не обнаруживается. Хотя просто *Макаров* из _Перм*_ выдаёт в т.ч. запись №544772 (*Макаров Павел Яковлевич*)

**Comment by a-KaDeMi-k** [comment]
Имя надо явно звёздочкой заменять - тогда ищет

**Comment by Limych** [comment]
Проблема не обнаружена.
http://1914dev.svrt.ru/index.php?surname=%D0%9C%D0%B0%D0%BA%D0%B0%D1%80%D0%BE%D0%B2&name=%D0%9F%D0%B0%D0%B2%D0%B5%D0%BB+%D0%AF%D0%BA%D0%BE%D0%B2%D0%BB%D0%B5%D0%B2%D0%B8%D1%87&place=%D0%9F%D0%B5%D1%80%D0%BC*#report

**Comment by Limych** [comment]
fixed
