### ISSUE TITLE
Оптимизация запросов пользователей

### ISSUE THREAD

**Issue by Limych** [Limych/GeniBase#63]
Упрощение запросов, типа
«к\*\*\*\*» → «к???\*»
«\*» → «»
«\* Петрович» → «Петрович»

**Comment by a-KaDeMi-k** [comment]
имхо, «к****» → «к*», т.е., фактически, «****» → «*»

**Comment by Limych** [comment]
Нет, ты не прав. Звёздочка означает «_один_ или более символов». А значит, «\*\*\*\*» не может быть соответствовать менее чем четырём символам. Но для системы будет проще, если она перепишет запрос именно так, как я указал.
А заодно и человек увидит ситуацию и, возможно, откорректирует запрос…

**Comment by a-KaDeMi-k** [comment]
Мне казалось, что мы звёздочкой заменили mysql-евский %, который означает любое кол-во символов, в т.ч. и их полное отсутствие...

**Comment by Limych** [comment]
Если чего-то кажется, — иди и читай мануалы…

Для того их и пишут.

**Comment by a-KaDeMi-k** [comment]
Мог бы просто написать, что меняешь звёздочку не на %, а на _%

**Comment by Limych** [comment]
Разговор изначально шёл про то, что звёздочка заменяет один или более символов — можешь перечитать форум.
