### ISSUE TITLE
Формализатор работает?

### ISSUE THREAD

**Issue by a-KaDeMi-k** [Limych/GeniBase#68]
Залил в raw новую порцию - счётчик стоит на месте, данные не формализуются.

В связи с этим несколько вопросов...
0. Ты формализатор принудительно отключил или это баг всплыл?
1. Можно ли перенастроить cron на управление не с твоего сайта, а с СВРТ-шного? Или это уже сделано?
2. Думаю, имеет смысл включить в формализатор индексирующий блок (продублировать его). Т.е., чтобы новые записи индексировались сразу при формализации. Или хотя бы, как минимум, чтобы фамильные индексы сразу строились (тип 100)
А в db_update тогда только при обновлении алгоритма индексирующий блок будет задействоваться.
3. Форма edit тоже не работает.

**Comment by Limych** [comment]
Я ничего не отключал.

Крон буду рад убрать с моего сайта. Но в последнее время местный крон был более чем неудобен.

Формализатор и индексатор сращивать не буду. Это разные системы.

**Comment by a-KaDeMi-k** [comment]
Кроме формализатора, похоже и индексатор застопорился %)

Максимальная дата обновления ключа - 2015-03-14 23:31:33

На текущий момент:
4 962 записи из persons до сих пор без индексов
86 251 уникальных фамилий по 99 841 записям попадают в отбор на индексацию

**Comment by Limych** [comment]
#70

**Comment by a-KaDeMi-k** [comment]
Формализатор отработал.

Но редактор edit выдаёт ошибку `Fatal error: Call to undefined function html_header() in /home/www/z77591/1914/edit/publish.php on line 152`
Осталась одна неформализованная запись - без него не могу врубиться в причину отказа в формализации.

Индексатор тоже заработал :+1: 
На текущий момент:
 8 920 записи из persons без индексов (добавились только что формализованные)
 5 861 уникальных фамилий по 9 292 записям попадают в отбор на индексацию
Чёто быстро как-то (со вчерашнего вечера) отиндексировалось. Да даже не с вечера, а когда ты там поправил... Хм...

**Comment by Limych** [comment]
fixed

**Comment by a-KaDeMi-k** [comment]
жесть!
пробел в поле "дате события" :)

**Comment by a-KaDeMi-k** [comment]
Для отслеживания динамики:
5 260 уникальных фамилий по 8 542 записям попадают в отбор на индексацию
8 233 записи из persons без индексов
Не густо за четверо суток :confused:
