### ISSUE TITLE
Неверный результат при поиске с подстановками

### ISSUE THREAD

**Issue by a-KaDeMi-k** [Limych/GeniBase#84]
Вроде бы ж тестировали такой вариант, но либо что-то правками попортили, либо у меня склероз.

Вообщем, ввожу в простом поиске фамилию _неж**е**нцев_ - в результатах две записи 
_неж**е**нцев_, шесть - _неж**и**нцев_, три неполных (буквы со звёздочками) и остальная кучка - простые звёздочки.

При поиске _неж**?**нцев_ (и даже _неж*нцев_) результатов должно быть никак не меньше. Но в обоих случаях записи _неж**е**нцев_ и _неж**и**нцев_ отсутствуют.

**Comment by Limych** [comment]
Fixed
